FROM node:20.13.0

WORKDIR /app

# Expose the port your application listens on (replace 3000 with your actual port)
EXPOSE 3000

# Start the application (adjust the command based on your entry point)
#CMD [ "npm", "start" ]